CREATE TABLE country
(
    id   UUID NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255),
    name        VARCHAR(255),
    brand       VARCHAR(255),
    type        VARCHAR(255),
    description VARCHAR(255),
    category    VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);