CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE categories_products
(
    category_id BIGINT NOT NULL,
    products_id BIGINT NOT NULL
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255),
    name        VARCHAR(255),
    brand       VARCHAR(255),
    type        VARCHAR(255),
    description VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE products_categories
(
    product_id    BIGINT NOT NULL,
    categories_id BIGINT NOT NULL
);

ALTER TABLE categories_products
    ADD CONSTRAINT fk_catpro_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE categories_products
    ADD CONSTRAINT fk_catpro_on_product FOREIGN KEY (products_id) REFERENCES products (id);

ALTER TABLE products_categories
    ADD CONSTRAINT fk_procat_on_category FOREIGN KEY (categories_id) REFERENCES categories (id);

ALTER TABLE products_categories
    ADD CONSTRAINT fk_procat_on_product FOREIGN KEY (product_id) REFERENCES products (id);