insert into categories (name, created_at, description) values ('Ecolab - Hobart Upr Prewash Arm', '1/8/2024', 'Reattachment of Right Knee Tendon, Open Approach');
insert into categories (name, created_at, description) values ('Halibut - Whole, Fresh', '12/24/2023', 'Reattachment of Right Shoulder Tendon, Open Approach');
insert into categories (name, created_at, description) values ('Vermouth - Sweet, Cinzano', '7/24/2023', 'Repair Lymph & Hemic in POC with Oth Dev, Perc Approach');
insert into categories (name, created_at, description) values ('Mountain Dew', '10/14/2023', 'Remove Tissue Expander from Up Extrem Subcu/Fascia, Open');
insert into categories (name, created_at, description) values ('Bread Base - Italian', '1/11/2024', 'Drainage of Left Vocal Cord, Percutaneous Approach');
insert into categories (name, created_at, description) values ('Sauce - Rosee', '3/22/2023', 'Resection of Thyroid Gland, Percutaneous Endoscopic Approach');
insert into categories (name, created_at, description) values ('Wine - Dubouef Macon - Villages', '12/17/2023', 'Restriction of Ileum with Intraluminal Device, Via Opening');
insert into categories (name, created_at, description) values ('Wiberg Cure', '10/30/2023', 'Extirpation of Matter from Thor Aorta Desc, Perc Approach');
insert into categories (name, created_at, description) values ('Baking Soda', '9/11/2023', 'Occlusion of Right Upper Extremity Lymphatic, Open Approach');
insert into categories (name, created_at, description) values ('Pork - Kidney', '9/14/2023', 'Plain Radiography of R Single Mamm Duct using H Osm Contrast');
insert into categories (name, created_at, description) values ('Olives - Stuffed', '12/27/2023', 'Bypass R Com Iliac Art to R Renal A w Nonaut Sub, Open');
insert into categories (name, created_at, description) values ('Wine - Blue Nun Qualitatswein', '9/5/2023', 'Restrict of R Axilla Lymph with Intralum Dev, Open Approach');
insert into categories (name, created_at, description) values ('Ginger - Fresh', '4/10/2023', 'Insertion of Infusion Device into L Brach Art, Open Approach');
insert into categories (name, created_at, description) values ('Spaghetti Squash', '2/8/2024', 'Excision of Right Inner Ear, Open Approach');
insert into categories (name, created_at, description) values ('Mix - Cappucino Cocktail', '2/12/2024', 'Occlusion of Right Vertebral Vein, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Placemat - Scallop, White', '1/27/2024', 'Supplement Aortic Valve with Synth Sub, Open Approach');
insert into categories (name, created_at, description) values ('Pork - Loin, Center Cut', '11/9/2023', 'Drain of L Knee Bursa/Lig with Drain Dev, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Tart - Butter Plain Squares', '8/28/2023', 'Plain Radiography of Right Hip using High Osmolar Contrast');
insert into categories (name, created_at, description) values ('Wine - Alsace Gewurztraminer', '3/10/2023', 'Alteration of R Elbow with Synth Sub, Perc Approach');
insert into categories (name, created_at, description) values ('Peach - Fresh', '9/22/2023', 'Destruction of Head Lymphatic, Percutaneous Approach');
insert into categories (name, created_at, description) values ('Glass Clear 7 Oz Xl', '11/14/2023', 'Fragmentation in Small Intestine, Via Opening');
insert into categories (name, created_at, description) values ('Praline Paste', '10/11/2023', 'Supplement Right Hepatic Duct with Autol Sub, Perc Approach');
insert into categories (name, created_at, description) values ('Cake - Pancake', '7/12/2023', 'Computerized Tomography (CT Scan) of Bi Int Carotid');
insert into categories (name, created_at, description) values ('Onions - Cooking', '8/17/2023', 'Occlusion Bi Sperm Cord w Extralum Dev, Perc Endo');
insert into categories (name, created_at, description) values ('Crab - Claws, Snow 16 - 24', '1/8/2024', 'Restrict Abd Aorta, Bifurc, w Fenestr Dev 3+, Open');
insert into categories (name, created_at, description) values ('Pepsi - 600ml', '6/13/2023', 'Computerized Tomography (CT Scan) of Mandible');
insert into categories (name, created_at, description) values ('Icecream Cone - Areo Chocolate', '2/22/2024', 'Peripheral Nervous System, Division');
insert into categories (name, created_at, description) values ('Tomatoes Tear Drop', '8/29/2023', 'Introduce Platelet Inhibitor in Central Vein, Perc');
insert into categories (name, created_at, description) values ('Oxtail - Cut', '3/17/2023', 'Transfer Left Trunk Bursa and Ligament, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Pasta - Fettuccine, Dry', '2/23/2024', 'Imaging, Heart, Fluoroscopy');
insert into categories (name, created_at, description) values ('Wine - Pinot Noir Mondavi Coastal', '9/27/2023', 'Exercise Treatment of Resp Head, Neck using Oth Equip');
insert into categories (name, created_at, description) values ('Flour - Semolina', '1/24/2024', 'Resection of Left Lacrimal Duct, Open Approach');
insert into categories (name, created_at, description) values ('Soupfoamcont12oz 112con', '12/15/2023', 'Replace of L Thumb Phalanx with Nonaut Sub, Perc Approach');
insert into categories (name, created_at, description) values ('Veal - Shank, Pieces', '4/17/2023', 'Replacement of Left Orbit with Nonaut Sub, Perc Approach');
insert into categories (name, created_at, description) values ('Beer - Upper Canada Light', '11/22/2023', 'Plain Radiography of Aorta, Bi LE Art using L Osm Contrast');
insert into categories (name, created_at, description) values ('Jolt Cola - Electric Blue', '12/6/2023', 'Revision of Drainage Device in Chest Wall, External Approach');
insert into categories (name, created_at, description) values ('Thyme - Lemon, Fresh', '7/28/2023', 'Removal of Infusion Device from Respiratory Tract, Endo');
insert into categories (name, created_at, description) values ('Cinnamon Buns Sticky', '1/6/2024', 'Excision of Left Abdomen Muscle, Perc Approach, Diagn');
insert into categories (name, created_at, description) values ('External Supplier', '5/30/2023', 'Beam Radiation of Jejunum using Neutrons');
insert into categories (name, created_at, description) values ('Salt - Table', '2/2/2024', 'Revision of Drain Dev in R Finger Phalanx Jt, Perc Approach');
insert into categories (name, created_at, description) values ('Peas - Pigeon, Dry', '3/19/2023', 'Drainage of R Thyroid Lobe with Drain Dev, Perc Approach');
insert into categories (name, created_at, description) values ('Quail Eggs - Canned', '2/11/2024', 'Revision of Autol Sub in Low Vein, Extern Approach');
insert into categories (name, created_at, description) values ('Avocado', '4/26/2023', 'Occlusion of R Ext Carotid with Intralum Dev, Perc Approach');
insert into categories (name, created_at, description) values ('Edible Flower - Mixed', '5/26/2023', 'Reposition Ascending Colon, Via Opening');
insert into categories (name, created_at, description) values ('Thyme - Dried', '1/11/2024', 'Replacement of L Toe Phalanx with Synth Sub, Open Approach');
insert into categories (name, created_at, description) values ('Pepper - Chilli Seeds Mild', '9/9/2023', 'Occlusion of Right Spermatic Cord, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Mini - Vol Au Vents', '6/27/2023', 'Supplement Pericardium with Autol Sub, Perc Approach');
insert into categories (name, created_at, description) values ('Veal - Leg', '10/31/2023', 'Release Upper Gingiva, External Approach');
insert into categories (name, created_at, description) values ('Hand Towel', '5/16/2023', 'Removal of Synth Sub from L Glenoid Cav, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Wine - Shiraz South Eastern', '9/17/2023', 'Restrict R Low Lobe Bronc w Extralum Dev, Perc');
insert into categories (name, created_at, description) values ('Beef - Tongue, Cooked', '11/2/2023', 'Dilate Splenic Art, Bifurc, w Drug-elut Intra, Perc');
insert into categories (name, created_at, description) values ('Grouper - Fresh', '2/4/2024', 'Excision of Bilateral Seminal Vesicles, Perc Approach, Diagn');
insert into categories (name, created_at, description) values ('Cilantro / Coriander - Fresh', '10/2/2023', 'Supplement Pulm Valve with Synth Sub, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Bread - Raisin Walnut Pull', '12/23/2023', 'Removal of Autol Sub from R Sternoclav Jt, Open Approach');
insert into categories (name, created_at, description) values ('Cheese - Gorgonzola', '8/13/2023', 'Insertion of Artif Sphincter into Anus, Perc Endo Approach');
insert into categories (name, created_at, description) values ('General Purpose Trigger', '5/14/2023', 'Excision of Left Brachial Artery, Percutaneous Approach');
insert into categories (name, created_at, description) values ('Chocolate - Pistoles, White', '9/25/2023', 'Revision of Nonaut Sub in L Acromioclav Jt, Perc Approach');
insert into categories (name, created_at, description) values ('Pepper - Green, Chili', '7/31/2023', 'Resection of Nasal Turbinate, Open Approach');
insert into categories (name, created_at, description) values ('Cafe Royale', '1/4/2024', 'Destruction of Right Lung, Open Approach');
insert into categories (name, created_at, description) values ('Venison - Liver', '5/15/2023', 'Change Oth Dev in Epididymis/Sperm Cord, Extern Approach');
insert into categories (name, created_at, description) values ('Crab - Imitation Flakes', '6/24/2023', 'Removal of Autol Sub from Lymph, Open Approach');
insert into categories (name, created_at, description) values ('Cornish Hen', '12/28/2023', 'Revision of Neuro Lead in Spinal Cord, Open Approach');
insert into categories (name, created_at, description) values ('Muffin Hinge Container 6', '5/11/2023', 'Insert of Monitor Dev into Abd Subcu/Fascia, Perc Approach');
insert into categories (name, created_at, description) values ('Wine - Red, Metus Rose', '7/7/2023', 'Release Perineum Bursa and Ligament, Open Approach');
insert into categories (name, created_at, description) values ('Bag - Regular Kraft 20 Lb', '1/24/2024', 'Removal of Int Fix from R Fibula, Perc Approach');
insert into categories (name, created_at, description) values ('Mussels - Frozen', '4/9/2023', 'Dilate 3 Cor Art, Bifurc, w 2 Intralum Dev, Perc Endo');
insert into categories (name, created_at, description) values ('Melon - Watermelon Yellow', '8/13/2023', 'Bypass R Popl Art to Low Ex Vein w Nonaut Sub, Perc Endo');
insert into categories (name, created_at, description) values ('Pastry - Raisin Muffin - Mini', '6/15/2023', 'Traction of Right Hand');
insert into categories (name, created_at, description) values ('Container - Clear 32 Oz', '6/29/2023', 'Supplement Right Pelvic Bone with Autol Sub, Perc Approach');
insert into categories (name, created_at, description) values ('Walkers Special Old Whiskey', '1/24/2024', 'Destruction of Left Kidney Pelvis, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Pepper - Red Bell', '4/3/2023', 'Revision of Extralum Dev in Fallopian Tube, Via Opening');
insert into categories (name, created_at, description) values ('Pan Grease', '3/18/2023', 'Bypass Ileum to Anus with Synth Sub, Open Approach');
insert into categories (name, created_at, description) values ('Bread - Dark Rye, Loaf', '10/24/2023', 'Dilation of L Ulnar Art with 3 Drug-elut, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Crab - Claws, Snow 16 - 24', '1/10/2024', 'Bypass R Com Iliac Art to R Renal A w Nonaut Sub, Open');
insert into categories (name, created_at, description) values ('Bay Leaf Fresh', '3/5/2024', 'Extirpate matter from Post Neck Subcu/Fascia, Perc');
insert into categories (name, created_at, description) values ('Bacardi Limon', '12/13/2023', 'Excision of Appendix, Percutaneous Endoscopic Approach');
insert into categories (name, created_at, description) values ('Nut - Pumpkin Seeds', '8/27/2023', 'Drainage of L Com Carotid, Perc Endo Approach, Diagn');
insert into categories (name, created_at, description) values ('Cocoa Butter', '8/10/2023', 'Revise of Infusion Dev in Trunk Subcu/Fascia, Perc Approach');
insert into categories (name, created_at, description) values ('Energy Drink - Franks Pineapple', '1/31/2024', 'Drainage of Inf Vena Cava with Drain Dev, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Sobe - Green Tea', '11/27/2023', 'Exercise Treatment of Neuro Body using Prosthesis');
insert into categories (name, created_at, description) values ('Cheese - Valancey', '10/10/2023', 'Drainage of Right Pleural Cavity, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Bread Sour Rolls', '11/12/2023', 'Repair Right Carotid Body, Percutaneous Approach');
insert into categories (name, created_at, description) values ('Turkey - Whole, Fresh', '10/28/2023', 'Drainage of Sacral Nerve, Open Approach');
insert into categories (name, created_at, description) values ('Coffee - Cafe Moreno', '11/7/2023', 'Drainage of Right Upper Arm, Percutaneous Approach');
insert into categories (name, created_at, description) values ('Spice - Onion Powder Granulated', '6/7/2023', 'Occlusion of Bladder with Extraluminal Device, Open Approach');
insert into categories (name, created_at, description) values ('Sole - Iqf', '2/13/2024', 'Extirpate matter from R Up Leg Subcu/Fascia, Open');
insert into categories (name, created_at, description) values ('Nut - Almond, Blanched, Whole', '6/16/2023', 'Release Lumbar Vertebral Disc, Percutaneous Approach');
insert into categories (name, created_at, description) values ('Doilies - 10, Paper', '12/28/2023', 'Supplement R Elbow Bursa/Lig w Synth Sub, Perc Endo');
insert into categories (name, created_at, description) values ('Apple - Royal Gala', '10/3/2023', 'Alteration of Lower Lip, External Approach');
insert into categories (name, created_at, description) values ('Lamb Tenderloin Nz Fr', '5/28/2023', 'Extirpation of Matter from Urethra, Percutaneous Approach');
insert into categories (name, created_at, description) values ('Buttons', '6/3/2023', 'Compression of Neck using Pressure Dressing');
insert into categories (name, created_at, description) values ('Wine - Gato Negro Cabernet', '9/26/2023', 'CT Scan of Facial Bone using Oth Contrast');
insert into categories (name, created_at, description) values ('Wine - Fontanafredda Barolo', '6/10/2023', 'Drainage of L Thorax Bursa/Lig with Drain Dev, Perc Approach');
insert into categories (name, created_at, description) values ('Pork - Back, Short Cut, Boneless', '10/31/2023', 'Reposition Right Upper Leg Muscle, Perc Endo Approach');
insert into categories (name, created_at, description) values ('Truffle Cups - Red', '1/12/2024', 'Extirpation of Matter from Left Carpal Joint, Open Approach');
insert into categories (name, created_at, description) values ('Lobster - Canned Premium', '9/30/2023', 'Replacement of R Hip Jt, Acetab with Ceramic, Open Approach');
insert into categories (name, created_at, description) values ('Dill - Primerba, Paste', '12/2/2023', 'Indiv Psychotherapy for Substance Abuse, Interactive');
insert into categories (name, created_at, description) values ('Napkin - Cocktail,beige 2 - Ply', '12/31/2023', 'Removal of Monitoring Device from Low Vein, Extern Approach');
insert into categories (name, created_at, description) values ('Five Alive Citrus', '6/12/2023', 'Removal of Infusion Device from Spinal Cord, Open Approach');
insert into categories (name, created_at, description) values ('Fiddlehead - Frozen', '6/19/2023', 'Drainage of Periton Cav with Drain Dev, Perc Endo Approach');